name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up semantic versioning
        id: version_bump
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          bump_each_commit: false
          version_format: "${major}.${minor}.${patch}"
          debug: true
          search_commit_body: true

      - name: Check commit message for tag or release
        id: tag_release_check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"tag"* ]]; then
            echo "Creating a new tag"
            echo "TAG=true" >> $GITHUB_ENV
          else
            echo "No tag to create"
            echo "TAG=false" >> $GITHUB_ENV
          fi

      - name: Create Git tag
        if: env.TAG == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ steps.version_bump.outputs.version_tag }} -m "Release version ${{ steps.version_bump.outputs.version_tag }}"
          git push origin ${{ steps.version_bump.outputs.version_tag }}